<script setup lang="ts">
    import FaqDisclosure from './FaqDisclosure.vue';
    import { ref } from 'vue';

    const openFaqDisclosure = ref<string>();

    const FAQ_QUESTIONS: { question: string; answer: string }[] = [
        {
            question: 'What are / what do the toppings do?',
            answer:
                'Toppings increase the number of tacos earned per-click by increasing your click multiplier. ' +
                'The more types of toppings unlocked increase the variety bonus which also increases the click ' +
                'multiplier. The click multiplier also applies to automatic clicks (i.e. Taco Truck, etc...).',
        },
        {
            question: 'What is the variety bonus?',
            answer: 'If you increase the variety of toppings purchased, a bonus to the click multiplier is added. The more variety, the more tacos you get for a single click!',
        },
        {
            question: 'How does the click multiplier work?',
            answer: 'Whenever you click, you earn one taco, plus the multiplier value. The multiplier also applies to clicks generated by automations like the taco truck.',
        },
    ];
</script>

<template>
    <div class="overflow-y-auto px-3 sm:px-10 sm:pt-6">
        <div class="mx-auto flex w-full max-w-5xl flex-col py-6">
            <h1 class="mb-4 text-2xl text-gray-100 sm:text-4xl">Who made this?</h1>

            <p class="text-gray-100 sm:text-lg">
                My girlfriend,
                <a href="https://art.devilsquares.me/" target="_blank" class="text-link">Devilsquares</a>
                 and I
                <a href= "https://iapetus11.me" target="_blank" class="text-link">(Iapetus11)</a>
                made this! We were bored, trying to brainstorm a project to work on for fun, and we came up
                with Spring Roll Clicker... Obviously that is not Taco Tapper, we figured since we both love
                tacos and there's more variety it would make a better game. We both hope the rare few who visit have
                lots of fun tapping and eating tacos :)
            </p>
        </div>

        <div class="mx-auto flex w-full max-w-5xl flex-col py-6">
            <h1 class="mb-4 text-2xl text-gray-100 sm:text-4xl">Frequently Asked Questions</h1>

            <div class="flex flex-col space-y-2.5">
                <FaqDisclosure
                    v-for="faqQuestion in FAQ_QUESTIONS"
                    :key="faqQuestion.question"
                    :title="faqQuestion.question"
                    v-model:open-id="openFaqDisclosure"
                >
                    <span v-html="faqQuestion.answer" />
                </FaqDisclosure>
            </div>
        </div>
    </div>
</template>
